name: Lint JavaScript com ESLint

on:
  push:
    branches: ["*"]
  pull_request:
    branches: ["*"]

jobs:
  lint-js:
    runs-on: ubuntu-latest
    steps:
      - name: Clonar repositório
        uses: actions/checkout@v3

      - name: Instalar Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "18"

      - name: Instalar dependências
        run: npm install

      - name: Rodar ESLint
        run: npx eslint "**/*.js"
